INSERT INTO HIBERNATE_SEQUENCES (ID, SEQUENCE_NAME, NEXT_VAL) VALUES (50, 'CATEGORY_ID', 50);
INSERT INTO HIBERNATE_SEQUENCES (ID, SEQUENCE_NAME, NEXT_VAL) VALUES (51, 'USERS_ID', 50);
INSERT INTO HIBERNATE_SEQUENCES (ID, SEQUENCE_NAME, NEXT_VAL) VALUES (52, 'INCOME_ID', 50);