CREATE TABLE CATEGORY (
    ID      NUMBER(12),
    NAME    VARCHAR2(30 CHAR) NOT NULL,
    
    CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (ID) 
);

CREATE TABLE USERS(
    ID NUMBER(12),
    NAME VARCHAR2(15 CHAR) NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY(ID)
);

CREATE TABLE BUDGET_TYPE(
    ID NUMBER(12),
    CODE VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_BUDGET_ID PRIMARY KEY(ID)
);

CREATE TABLE BUDGET_RECORD(
    ID NUMBER(12),
    CATEGORY_ID NUMBER(12) NOT NULL,
    BUDGET_TYPE_ID NUMBER(12) NOT NULL,
    USER_ID NUMBER(12) NOT NULL,
    CREATED DATE NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    CONSTRAINT PK_BUDGET_RECORD_ID PRIMARY KEY(ID)
);

ALTER TABLE BUDGET_RECORD ADD CONSTRAINT FK_BUDGET_REC_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE BUDGET_RECORD ADD CONSTRAINT FK_BUDGET_REC_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);
ALTER TABLE BUDGET_RECORD ADD CONSTRAINT FK_BUDGET_REC_BUDGET_TYPE FOREIGN KEY (BUDGET_TYPE_ID) REFERENCES BUDGET_TYPE(ID);

