CREATE TABLE HIBERNATE_SEQUENCES (
    ID              NUMBER(12),
    SEQUENCE_NAME   VARCHAR2(30) NOT NULL,
    NEXT_VAL        NUMBER(12),
    
    CONSTRAINT PK_HIBERNATE_SEQUENCES PRIMARY KEY(ID)
);

CREATE TABLE CATEGORY (
    ID      NUMBER(12),
    NAME    VARCHAR2(30 CHAR) NOT NULL,
    
    CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (ID) 
);
