CREATE TABLE HIBERNATE_SEQUENCES (
    ID              NUMBER(12),
    SEQUENCE_NAME   VARCHAR2(30) NOT NULL,
    NEXT_VAL        NUMBER(12),
    
    CONSTRAINT PK_HIBERNATE_SEQUENCES PRIMARY KEY(ID)
);

CREATE TABLE CATEGORY (
    ID      NUMBER(12),
    NAME    VARCHAR2(30 CHAR) NOT NULL,
    
    CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (ID) 
);

CREATE TABLE USERS(
    ID NUMBER(12),
    NAME VARCHAR2(15 CHAR) NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY(ID)
);

CREATE TABLE INCOME(
    ID NUMBER(12),
    CATEGORY_ID NUMBER(12) NOT NULL,
    USER_ID NUMBER(12) NOT NULL,
    CREATED DATE NOT NULL,
    AMOUNT NUMBER(15) NOT NULL,
    CONSTRAINT PK_INCOME_ID PRIMARY KEY(ID)
);

ALTER TABLE INCOME ADD CONSTRAINT FK_INCOME_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE INCOME ADD CONSTRAINT FK_INCOME_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);

