package com.homeacc.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
* BudgetType generated by hbm2java
*/
@Entity
@Table(name = "BUDGET_TYPE")
public class BudgetType implements java.io.Serializable {

	private long id;
	private String code;
	private Set<Income> incomes = new HashSet<Income>(0);

	public BudgetType() {
	}

	public BudgetType(long id, String code) {
		this.id = id;
		this.code = code;
	}

	public BudgetType(long id, String code, Set<Income> incomes) {
		this.id = id;
		this.code = code;
		this.incomes = incomes;
	}

	@Id
	@GeneratedValue(generator = "generator", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "generator", sequenceName = "budget_type_id", initialValue = 50, allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	public Set<Income> getIncomes() {
		return this.incomes;
	}

	public void setIncomes(Set<Income> incomes) {
		this.incomes = incomes;
	}

}

