package com.homeacc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
* Groups generated by hbm2java
*/
@Entity
@Table(name = "GROUPS")
public class Groups implements java.io.Serializable {

	private long id;
	private String name;
	private String password;

	public Groups() {
	}

	public Groups(long id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	@Id
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator",
		    strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
		    @Parameter(name = "sequence_name", value = "seq_group"),
		    @Parameter(name = "initial_value", value = "50"),
		    @Parameter(name = "increment_size", value = "1"),
		    @Parameter(name = "value_column", value = "seq_count") })
	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PASSWORD", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
